# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter:  postgresql
  encoding: unicode
  host:     <%= ENV["DB_HOST"] %>
  port:     <%= ENV["DB_PORT"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>
  pool:     5
  template: template0


development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] + "/hogemint_development" %>
  database: hogemint_development
  
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] + "/hogemint_production" %>
  database: hogemint_production
  
test:
  <<: *default
  url: <%= ENV["DATABASE_URL"] + "/hogemint_test" %>
  database: hogemint_test
  